name: Build

on:
  workflow_call:
    inputs:
      version:
        description: ""
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      # TEST
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.version }}

      - name: Notice
        run: |
          echo "${GITHUB_REF_TYPE}-${GITHUB_REF_NAME//[\/]/-}.${GITHUB_SHA::8}"
          echo '${{ github.ref_name }}'
          git status
