name: Build

on:
  workflow_call:
    inputs:
      version:
        description: ""
        type: string
        required: true

env:
  GITHUB_REF_NAME: ${{ inputs.version }}
  GITHUB_REF: refs/tags/${{ inputs.version }}
  GITHUB_REF_TYPE: tag

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      # TEST
      - name: Checkout
        uses: actions/checkout@v2

      - name: Notice
        run: |
          echo "${GITHUB_REF_TYPE}-${GITHUB_REF_NAME//[\/]/-}.${GITHUB_SHA::8}"
          echo '${{ github.ref_name }}'
