name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New application version, must follow semver."
        type: string
        required: true
        default: "auto"

jobs:
  release:
    runs-on: [ self-hosted, linux, default ]
    timeout-minutes: 15
    permissions:
      contents: write
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Determine Version
        id: version
        run: echo "::set-output name=version::$VERSION"
        env:
          VERSION: ${{ github.event.inputs.version }}
