name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New application version, must follow semver."
        type: string
        required: true
        default: "auto"

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Determine Version
        id: version
        run: echo "::set-output name=version::$VERSION"
        env:
          VERSION: ${{ github.event.inputs.version }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}

  build:
    needs: [release]
    uses: mdvorak/test-repo/.github/workflows/build.yaml@main
    with:
      version: ${{ needs.release.outputs.version }}
