name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New application version, must follow semver."
        type: string
        required: true
        default: "auto"

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Determine Version
        id: version
        run: echo "::set-output name=version::$VERSION"
        env:
          VERSION: ${{ github.event.inputs.version }}

      - name: Release
        uses: elgohr/Github-Release-Action@v3.1
        with:
          release: ${{ steps.version.outputs.version }}
